# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/website',
                'doc_host': 'https://mohammed8079.github.io',
                'git_url': 'https://github.com/mohammed8079/website',
                'lib_path': 'website'},
  'syms': {'website.core': {'website.core.foo': ('core.html#foo', 'website/core.py')}}}
